seminar-7/soCRUSHator/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Хотим, чтобы корнем приложения была форма создания ссылки.
  root 'link#index'
  # По умолчанию метод был get, но мы отправляем форму методом post, чтобы не использовать
  # query-параметры. Также мы явно указали название (as: :link_add), чтобы использовать хелпер link_add_url.
  # В целом так можно и не делать, но при использовании Rails-умолчаний при изменении пути изменится
  # и название хелпера, а нам было бы удобно, если оно останется как есть - чтобы не переделывать представления.
  # match нужно использовать, если маршрут можно дернуть несколькими методами. В данном случае get нужен просто для
  # улучшения UX - чтобы при обновлении страницы со ссылкой не было ошибки, что нельзя дергать методом get,
  # а был редирект на /.
  match 'link/add', via: %i[get post], as: :link_add
  # Для сокращенной ссылки нужен более короткий маршрут, причем в маршруте должен быть ПАРАМЕТР - часть,
  # которая меняется от запроса к запросу. В нашем случае мы будем передавать slug. И так как Rails не
  # сможет воспользоватеся никакими своими умолчаниями, мы должны явно указать, какой контроллер и какой экшн
  # использовать, а также как назвать хелпер.
  get 'r/:slug', to: 'link#redirect', as: :link_redirect
  get 'links', to: 'link#all', as: :link_all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

seminar-7/soCRUSHator/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

seminar-7/soCRUSHator/app/models/link.rb
# frozen_string_literal: true

# Это класс модели, который будет реализовывать всю бизнес-логику, которую мы заложили в приложение.
# Одной модели вполне достаточно, потому что и бизнес-логики немного.
class Link < ApplicationRecord
  # Мы хотим проверять, что url валиден. По умолчанию в Rails-моделях нет такого валидатора, поэтому
  # мы напишем его сами (app/validators/correct_uri_validator.rb). Он подключается рельсовой магией:
  # 1) все, что лежи в app, зарекваерится автоматом, так что наш валидатор уже виден везде без доп. усилий;
  # 2) для того, чтобы валидатор был валидатором, его нужно наследовать от чего надо;
  # 3) чтобы модели были доступны валидаторы, надо примешать ActiveModel::Validations; можно было и в
  # ApplicationRecord, но мы соберем все в одном месте для наглядности.
  # Наконец, валидатором можно пользоваться, НО тут в дело опять вступает рельсовая магия - валидатор
  # нигде не вызывается напрямую, однако если передать в качестве аргумента в validates название валидатора,
  # ОНО ЗАРАБОТАЕТ!!! Мы назвали валидатор CorrectUriValidator, значит, передавать нужно correct_uri: true.
  include ActiveModel::Validations

  # Сколько элементов выводить на страницу по умолчанию - просто чтобы быстрее увидеть пагинацию.
  paginates_per 5

  # Методы, которые выполняют проверки ограничений бизнес-логики.
  # В нашем случае необходимо, чтобы url и slug были определены, а также чтобы slug был уникальным.
  # Эти проверки делаются КОДОМ. Иными словами, код генерирует запросы к БД.
  # Например, проверка уникальности - это SELECT * FROM links WHERE slug = ? LIMIT 1; - если есть
  # хотя бы одна запись с тем же slug, проверка не пройдет.
  # Однако нужно понимать, что это ненадежная проверка, и она может не сработать при конкурентном
  # доступе к БД.
  # Именно поэтому мы добавили еще одну миграцию, в которой сделали уникальный индекс по slug.
  # Ко всему прочему, это позволит искать ссылки по slug (читай - делать редирект) быстрее.
  validates :url, presence: true, correct_uri: true
  validates :slug, presence: true, uniqueness: true

  # Это просто идиоматичный способ создать статический метод
  class << self
    # С помощью этого метода будем создавать новые ссылки.
    def create_from_link(link)
      # create - это то же самое, что Link.create; метод наследуется от ActiveRecord::Base.
      create url: link, slug: Nanoid.generate(size: 10)
    end

    # Занесем бизнес-логику в модель - нашли, увеличили счетчик просмотров, вернули.
    def find_and_increment_clicks(slug)
      link = find_by slug: slug
      return link unless link

      link.clicks += 1
      link.save

      link
    end
  end
end

seminar-7/soCRUSHator/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Чтобы локаль, если передана, бралась из параметров запроса.
  around_action :switch_locale

  # Чтобы легко и непринужденно кидать 404. То, что будет страница с ошибкой, норм,
  # потому что в продакшне эту ошибку "перехватит" nginx и отдаст нужную страницу.
  def not_found
    raise ActionController::RoutingError, 'Not Found'
  end

  private

  # Чтобы локаль, если передана, бралась из параметров запроса.
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

seminar-7/soCRUSHator/app/controllers/link_controller.rb
# frozen_string_literal: true

# Все, что нам нужно для работы со ссылками.
class LinkController < ApplicationController
  # Главная страница - просто отдает форму добавления ссылки.
  def index; end

  # Добавляет ссылку с базу.
  # Если запросить с методом get, редиректнет на /, это просто для улучшения UX.
  # Если запросить с методом post, постарается добавить ссылку в базу. Если получится, отрендерит страницу ссылки.
  # Не получится - отрендерит ошибку.
  # I18n.t :no_url_provided - это перевод. По умолчанию установлена русская локаль, все локали лежат в config/locales
  # Там ключу YAML-файла (например, no_url_provided) ставится в соответствие строка. Содержимое строки - перевод на язык.
  def add
    case request.method_symbol
    when :get
      redirect_to root_url
    else
      if params[:url]
        @link = Link.create_from_link(params[:url])
        @shorten_link = link_redirect_url slug: @link.slug
      else
        @error = I18n.t :no_url_provided
      end
    end
  end

  # В параметрах маршрута передается slug, ищется ссылка, увеличивается счетчик кликов, делается редирект.
  def redirect
    link = Link.find_and_increment_clicks params[:slug]
    not_found unless link
    redirect_to link.url
  end

  # Для сокращатора не нужен, но для 11 лабы - да.
  def all
    respond_to do |format|
      # Просто рендерит содержимое БД в виде XML.
      # Вообще говоря, НИКТО И НИКОГДА НЕ ОТДАЕТ ВСЮ БД, потому что там может ненормально огромное количество записей,
      # на считывание которого не хватит ни памяти, ни других ресурсов. Поэтому здесь это просто учебная задача.
      format.xml { render xml: Link.all.to_xml }
      # Обычно отдают по страницам.
      format.html { @links = Link.order(clicks: :desc).page params[:page] }
    end
  end
end

seminar-7/soCRUSHator/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

seminar-7/soCRUSHator/app/helpers/link_helper.rb
# frozen_string_literal: true

module LinkHelper
end

seminar-7/soCRUSHator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoCRUSHator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

seminar-7/soCRUSHator/app/views/link/add.html.erb
<main class="container vh-100 d-flex justify-content-center align-items-center">
  <% if @error %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= t :link_add_error %></h4>
      
      <p><%= @error %></p>

      <hr/>

      <%= link_to t(:link_to_root), root_url %>
    </div>
  <% elsif !@link.errors&.empty? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= t :link_add_error %></h4>
      
      <% @link.errors.each_entry do |field_name, error| %>
        <p><%= field_name %> <%= error %></p>
      <% end %>

      <hr/>

      <%= link_to t(:link_to_root), root_url %>
    </div>
  <% else %>
    <div class="card shadow p-3 mb-5 bg-white rounded">
      <div class="card-body">
        <h5 class="card-title"><%= t :link_added %></h5>

        <p><%= t :your_link_is %>: <a href="<%= @link.url %>" target="_blank"><%= @link.url %></a></p>

        <p><%= t :shorten_link_is %> <a href="<%= @shorten_link %>" target="_blank"><%= @shorten_link %></a></p>
        <small><a class="btn-copy-to-clipboard" data-toggle="tooltip" data-placement="top" title="<%= t :copied %>" href="#" data-copy-content="<%= @shorten_link %>"><%= t :click_to_copy %></a></small>
        
        <hr/>

        <p><%= link_to t(:link_to_root), root_url %></p>
      </div>
    </div>
  <% end %>
</main>

seminar-7/soCRUSHator/app/views/link/all.html.erb
<ul>
  <% @links.each do |link| %>
    <li>
      <%= link.url %> <%= link.slug %> <%= link.clicks %>
    </li>
  <% end %>
</ul>

<%= paginate @links, theme: 'twitter-bootstrap-4' %>

<%= link_to t(:link_to_root), root_url %>

seminar-7/soCRUSHator/app/views/link/index.html.erb
<main class="container vh-100 d-flex flex-column justify-content-center align-items-center">
  <div>
    <h2><%= t :shorten_link %></h2>

    <%= bootstrap_form_with url: link_add_url, method: :post, local: true do |f| %>
      <%= f.text_field :url, required: true, label: Link.human_attribute_name('url'), label_as_placeholder: true %>
    
      <div class="d-flex justify-content-end align-items-center">
        <%= f.submit t(:shorten_link), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <div class="mt-3 d-flex flex-column justify-content-center align-items-start">
    <p><%= link_to t(:links_as_html), link_all_url %></p>
    <p><%= link_to t(:links_as_xml), link_all_url(format: :xml) %></p>
  </div>
</main>